#ifndef CHTTP_TLS_TEST_MATERIAL_H
#define CHTTP_TLS_TEST_MATERIAL_H

/*
 * GmSSL validates endpoint certificates and trust anchors strictly.
 * The leaf and root use >=4-byte serial numbers and a fixed 3651-day validity
 * window within GmSSL's X509_VALIDITY_MAX_DAYS contract.
 */
static const char CHTTP_TLS_TEST_CERTIFICATE[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIDkDCCAnigAwIBAgIEEjRWeDANBgkqhkiG9w0BAQsFADA/MQswCQYDVQQGEwJV\n"
    "UzETMBEGA1UECgwKQ0hUVFAgVGVzdDEbMBkGA1UEAwwSQ0hUVFAgVGVzdCBSb290\n"
    "IENBMB4XDTI1MDEwMTAwMDAwMFoXDTM0MTIzMTAwMDAwMFowNjELMAkGA1UEBhMC\n"
    "VVMxEzARBgNVBAoMCkNIVFRQIFRlc3QxEjAQBgNVBAMMCWxvY2FsaG9zdDCCASIw\n"
    "DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAIi/iEXOmcYs0rUDI1EKH0tdaWGd\n"
    "Ruz3+x1647po+CrPzWUL/2LEJ3vUYegxc4z+Xmtk7OHanCZ94UpFANnVaboqbcYs\n"
    "7jsw6qaeCUJkhXW4M6PRwAFjjhu0vuBpZNRMSaS8RnPPLcH1nPHr6TXt8ZYOBDDb\n"
    "A2tre6zVCY3RITFJIQAZplBcaCIt05vZoa5acLEuMWTItOwsH4V9qkZXS77JMsAv\n"
    "NBhpC1XkVL5SAwBAn+v+KJqsYhJecskupDQXtKbzM7yS92HamAfkzihURVhI1mYb\n"
    "yBjFfO62RBPN5697HYFyhbYMxzA6VxXo8FRvFIo6AFTsxtYcnd8Q9+ojoUsCAwEA\n"
    "AaOBnDCBmTAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAU\n"
    "BggrBgEFBQcDAQYIKwYBBQUHAwIwGgYDVR0RBBMwEYIJbG9jYWxob3N0hwR/AAAB\n"
    "MB0GA1UdDgQWBBT5VXtF3GJgXZplNjygYkPcKZm4xDAfBgNVHSMEGDAWgBSmYT9w\n"
    "05DOgiN8ggnr6nNs8r7vFDANBgkqhkiG9w0BAQsFAAOCAQEAcKCn0j/YwRJ9CqIe\n"
    "5v9eXsNoyiOfKe6zA6qM+Rpa/Oh0QWvq55ury3FON+Bnc2RKDNg0zGCA9dKyuuSA\n"
    "0CzEaWemackKQz/Zgkl/LpmxO0fuinMEQ6rcm7pWfMgH7/rhdG0GkvalbI5P32pQ\n"
    "cPvVN3J9CnLmcQ21YGN+Zhe/u2vH1MROQ2cotX2ArKRqghO44pnz/W2smh2pvXeV\n"
    "g68P94SGH6k0FdznsPFG/ggOI0aPrJN5pc44YG60TUnvx4MwTUlNB+g8jpOWVn1l\n"
    "2Y9mZRt9FP8sHHLP9cPv92X6o+4stv+eRDeCa/ARAplGLvPAlzUh25RtQP2WY9qY\n"
    "fydmUA==\n"
    "-----END CERTIFICATE-----\n";

static const char CHTTP_TLS_TEST_CA_CERTIFICATE[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIDQTCCAimgAwIBAgIEI0VniTANBgkqhkiG9w0BAQsFADA/MQswCQYDVQQGEwJV\n"
    "UzETMBEGA1UECgwKQ0hUVFAgVGVzdDEbMBkGA1UEAwwSQ0hUVFAgVGVzdCBSb290\n"
    "IENBMB4XDTI1MDEwMTAwMDAwMFoXDTM0MTIzMTAwMDAwMFowPzELMAkGA1UEBhMC\n"
    "VVMxEzARBgNVBAoMCkNIVFRQIFRlc3QxGzAZBgNVBAMMEkNIVFRQIFRlc3QgUm9v\n"
    "dCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKtItcc0ld+RaPPW\n"
    "y1CO2TzMFgMfADgNtS0ZQBVdz8U/KGhzlew80wVXQkIP3XeUEx68jDyQMGE9j4mO\n"
    "b75cqgNXdV3sUhmairBFYoiV8jdW+rZtKIidqnMlHqwTll5AhZZSGsrbLKo7gt5v\n"
    "1sODGPCHHFamu3EmnNd4ht4oPUrPcI3Jp6OWN0cZpf0XA+8ZAfCqnwrZwr5RMQt2\n"
    "uILyy75tyM11hpEZh8h4kce2UXYhfsghmZ4zfk1gsMcGULw7x5gh7nOhMjHOO+6U\n"
    "UYDxPG2oPcKZ2CSyuBo+ethB9y2cgqnx3I/9Z0wDfh1fyTxEXOJtueX67D61N8D3\n"
    "Bv7wVDUCAwEAAaNFMEMwEgYDVR0TAQH/BAgwBgEB/wIBATAOBgNVHQ8BAf8EBAMC\n"
    "AQYwHQYDVR0OBBYEFKZhP3DTkM6CI3yCCevqc2zyvu8UMA0GCSqGSIb3DQEBCwUA\n"
    "A4IBAQCai0OhMyKufEG5KGJwzNJBSMKvpOAf4FYZmax4CqikEuTL3cTKwlhQxUsD\n"
    "wShhAxll1W3dcNQKImrf53Tac0B0On55UNg/XMJUcO9FE1unGBBTd/MOJbIDMG5C\n"
    "rpwJMp/1X6K8lAQdGMQZqppOip5Ys9ZukphOMiV+qJjxWg88eobVeym/nJp0oFPL\n"
    "y+Z01Af/j9OK40oDTsxgOISbJUc5GNL7XpQ9uBs2qm3V8ncW63fqQqZXcObXq2kf\n"
    "zZxbgiVmbK3hGN7oDFO5eQ0HEAUTDPRtNQJD3kfpKixoQKmpzu7GBndwg3dAzNqD\n"
    "ItaOTQxPoY3nGpVJj+2HHgYLnMkO\n"
    "-----END CERTIFICATE-----\n";

static const char CHTTP_TLS_TEST_KEY[] =
    "-----BEGIN PRIVATE KEY-----\n"
    "MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCIv4hFzpnGLNK1\n"
    "AyNRCh9LXWlhnUbs9/sdeuO6aPgqz81lC/9ixCd71GHoMXOM/l5rZOzh2pwmfeFK\n"
    "RQDZ1Wm6Km3GLO47MOqmnglCZIV1uDOj0cABY44btL7gaWTUTEmkvEZzzy3B9Zzx\n"
    "6+k17fGWDgQw2wNra3us1QmN0SExSSEAGaZQXGgiLdOb2aGuWnCxLjFkyLTsLB+F\n"
    "fapGV0u+yTLALzQYaQtV5FS+UgMAQJ/r/iiarGISXnLJLqQ0F7Sm8zO8kvdh2pgH\n"
    "5M4oVEVYSNZmG8gYxXzutkQTzeevex2BcoW2DMcwOlcV6PBUbxSKOgBU7MbWHJ3f\n"
    "EPfqI6FLAgMBAAECggEAElQC1UG1bZDTZZcilCQ0VpBnZUHEYFLKXESnd3QbPaMK\n"
    "x0N+OsQfUKMCGQdhEowt+9yT5/Tkyenu7gU6nHep9d2QR1Kn/tSgbALcKy24OjNy\n"
    "mb8tVLeoXoFGtg2aNIl3CLaCsNdGAuxDA/ptEEvbKJP/WXb5Sdv8QF7GADUqlZAi\n"
    "nd93DhH1iplE6S0gPZflXJ1XqciZBCkTtCCdzBeNhrX92BLalK0JWkYhEbskfXU1\n"
    "dbWPlPwgSD1Rn6t/V798P6sIqzUiqBm+w6E3rlH7qfocbZC1wWkdZTfahZPRy/Md\n"
    "AbSIGoiZ8F0/FCBKlDJHE/M9KaIh9r+aG1IDn513TQKBgQDAcxis2ld4Zc+iLEMp\n"
    "LQt4GmfMCBA3XGcLSHd6zYz/B52/DLXO7YSPmTbbCf+eYYdVSwascwOqkERrnCiT\n"
    "tRl2hYcRE/2MS0BsxiMfXEuJ1gW2x1qcPO8nbzNvoQTuAMOr9Nh5O2DZQGG0CjgQ\n"
    "BO4Cm0WoXKEID3lQjRaXnn8UhQKBgQC156o6ZNGcHmLhVrx3wWrdFMZqwA/Hcena\n"
    "hYQ6SICTSTULMmb4rSysXrxjKkwZ4seueuTN+0LZZH4ponjoZBkKhp0I6X57ETBn\n"
    "IMj295/j/xqqAKgPEzhn5eDn8XOTdw2k9x+kjFT/SKEgywmp5fJ5C3GS9Qcn4Q9u\n"
    "onT4FLPvjwKBgFGkwnQaUP9v2c1ID9n5FSOHuD8zsIV7+u8reByt9UIAXii94Kd/\n"
    "1jwBWOdF756ma36AzLz+MjD68TvhzMkVDE9eyHUzUN5i0lsTF7VnN1irZlMrccJU\n"
    "i3TkVSLnYasCwgBCaE/OJAEmsgxqRWxuWvbaHowVd+9ueR32LP53rBvtAoGAciZM\n"
    "dpRpzRRsbIfngScJDm9JDBg2Tqw3Wf/LOF/i/4pDFSGt6IOTsx9IDNqwItZjBCTu\n"
    "jCwOiSk82pewU/TsmeRbiworasMgora6JfDCj2q4qtH6pGslTF2/Qw4LvxBIqarC\n"
    "WpoNhJ1pL5D6IXnBLSB3RwcoVGgxLPYZfMxRFhUCgYBFnTy5SDZcr4JOZVlwNTiP\n"
    "9en/jwGWMQWSrW3W9IrI8R8CWJXXCZompC5/dGrTXxToqGpjvlD7WJ6qV9sqBQb/\n"
    "nS2ge4J2JhOZUPyJzd+GtnVj6UGcV7UyoQmC71sKW5z/+Dc6Yi75f4KfKRW40ZWC\n"
    "pn/+nEYRdDeagdm/eW9JdA==\n"
    "-----END PRIVATE KEY-----\n";

#endif /* CHTTP_TLS_TEST_MATERIAL_H */
