#ifndef CHTTP_TLS_TEST_MATERIAL_H
#define CHTTP_TLS_TEST_MATERIAL_H

/*
 * GmSSL validates trust anchors as CAs. Keep this fixture as a real chain:
 * localhost leaf first, then the test root CA. The leaf is valid for both
 * serverAuth and clientAuth because the same material is used by mTLS tests.
 * Dates are fixed so CI clock skew cannot make the certificate "not yet valid".
 */
static const char CHTTP_TLS_TEST_CERTIFICATE[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIDSjCCAjKgAwIBAgICA+owDQYJKoZIhvcNAQELBQAwHTEbMBkGA1UEAwwSQ0hU\n"
    "VFAgVGVzdCBSb290IENBMB4XDTI1MDEwMTAwMDAwMFoXDTM2MDEwMTAwMDAwMFow\n"
    "FDESMBAGA1UEAwwJbG9jYWxob3N0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB\n"
    "CgKCAQEAx02Z3M0Y39R8aGxGmO0EW+L5D8TRMqOch3Iqi9GHGTP58cYMoLEqrx6K\n"
    "BzKRPdKwsbURhAvGuErNlu5BDikcynCX0zxlhwRP6rOAZWgHKaxpKBrriOBbIzUs\n"
    "Ls/6yuX11pFmYEiB4lfOjVOJnJXIUSVEy7I13T9o12oMOf4owGhixFCCRPl8Q1xB\n"
    "u1x2DR/SJplVxMjsrBMUm1NnielmUziQwVJQLr6bPZ6QJnzgVm+VQ5D87Zj69CMp\n"
    "Mux3RxbV39iNU6vhAwBSAiN2qzxof5J+kehIQH/M3X/RANCRwhcGUNPsDEgmePdD\n"
    "tONVa1Jj8KApFBdzLXmVVVVaF/HrowIDAQABo4GcMIGZMAwGA1UdEwEB/wQCMAAw\n"
    "DgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAa\n"
    "BgNVHREEEzARgglsb2NhbGhvc3SHBH8AAAEwHQYDVR0OBBYEFL5IPnQdrVbVHJAE\n"
    "LCCAHAo19IEdMB8GA1UdIwQYMBaAFHsaRwVhYKxV8r18C3Is6njxjDNKMA0GCSqG\n"
    "SIb3DQEBCwUAA4IBAQBysbBEYRpEtEJmjUBbI80u1JCXRcm3zmHYJXaVM3gRDyKV\n"
    "NIon1KIjpI7EAO4lKy9kydismtXMZ01ko5oSvQ9tIwECG1dqePmOt8WczSCMcV06\n"
    "Zhh+0iVQ5zsI1DlfQnUT860e2xXfpLe83L6Z9h8f5YIoibA+nYqkOTQC14K/TgJB\n"
    "b6qZ2rqnRYHIx8J6AvyL4ja0rNOLYzAB5WU0LoqzCwzS4gN5M513XWV+7EQO30go\n"
    "sIN+jyDLb6l6By5b1HANXPQGqSVr7dyTQksgma6aLC1JCh+dzOoCfnv+4z9DSxjg\n"
    "0LOEcIsAoT6GrIGWNAbMEq+R0MSiJImGxPr0PzX8\n"
    "-----END CERTIFICATE-----\n"
    "-----BEGIN CERTIFICATE-----\n"
    "MIIDHDCCAgSgAwIBAgICA+kwDQYJKoZIhvcNAQELBQAwHTEbMBkGA1UEAwwSQ0hU\n"
    "VFAgVGVzdCBSb290IENBMB4XDTI1MDEwMTAwMDAwMFoXDTM2MDEwMTAwMDAwMFow\n"
    "HTEbMBkGA1UEAwwSQ0hUVFAgVGVzdCBSb290IENBMIIBIjANBgkqhkiG9w0BAQEF\n"
    "AAOCAQ8AMIIBCgKCAQEAqpYmYAefwGnWMLdyL8AKv1EFpNYJhl02cxEpe+1mQFMI\n"
    "sKbepuE6xb8p3ChsylMrPEwL/OBkTVj2dAzXikx6XY0VdhweHUX8I6/Y6TLwACxm\n"
    "CHFdUL1Ddr4XxqwkwwEWtcOJ24fp9akdtXyyPaORYFxbMNcF9Hl8Weeux8ABJp2X\n"
    "ftwF7yiDn5dmyHOIr9pusUZ8ZvVlixhY+SwoHcD2dUQivzJ7XSsD5aNVQWZHbIV1\n"
    "dt7Xa9+PAC8X2+il5R+4z96S+nxzR8DTjLYXVj52rZfvR+4W+felPxyvSWV9A4Dm\n"
    "xWxfboSBiXLV6HnETZ3Tio5m2GxnIo4+WR8CLb+eeQIDAQABo2YwZDASBgNVHRMB\n"
    "Af8ECDAGAQH/AgEBMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUexpHBWFgrFXy\n"
    "vXwLcizqePGMM0owHwYDVR0jBBgwFoAUexpHBWFgrFXyvXwLcizqePGMM0owDQYJ\n"
    "KoZIhvcNAQELBQADggEBACEvHOLYOhGSNxrMVs518BbWyQOZrJFNFOtXcjChgF0r\n"
    "re95hPmaSTdpYuZ30rvPjF2m81GHg3Zh1aI0KdPUDOQiSDrxW0yc9FonhZ4MIWOk\n"
    "+d4waUO9rR+C6BkmBQ+NqxU71vOF4uH2m5KBQxIs4wdyCppQILfL2zpo/112UOnh\n"
    "YtfU1U9d7TM061Oxu8YhY5BsZp+y6YFIgTDRn6D4bKHanXPZBKpSfgz6IeiblU/m\n"
    "tcOvMoezQ1/u071PwUILNpArj6OR/YplYCNJVkHPZWGyxDS9FWqY1GCyRLcJYUsj\n"
    "P02fKZQJIJtOkow5hLMpcSEXsmkN21madAsDwqgqr9U=\n"
    "-----END CERTIFICATE-----\n";

static const char CHTTP_TLS_TEST_KEY[] =
    "-----BEGIN PRIVATE KEY-----\n"
    "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDHTZnczRjf1Hxo\n"
    "bEaY7QRb4vkPxNEyo5yHciqL0YcZM/nxxgygsSqvHooHMpE90rCxtRGEC8a4Ss2W\n"
    "7kEOKRzKcJfTPGWHBE/qs4BlaAcprGkoGuuI4FsjNSwuz/rK5fXWkWZgSIHiV86N\n"
    "U4mclchRJUTLsjXdP2jXagw5/ijAaGLEUIJE+XxDXEG7XHYNH9ImmVXEyOysExSb\n"
    "U2eJ6WZTOJDBUlAuvps9npAmfOBWb5VDkPztmPr0Iyky7HdHFtXf2I1Tq+EDAFIC\n"
    "I3arPGh/kn6R6EhAf8zdf9EA0JHCFwZQ0+wMSCZ490O041VrUmPwoCkUF3MteZVV\n"
    "VVoX8eujAgMBAAECggEAEwnmM1ICWMtvEPia69vkaTSu7yMxisFXYBb3WoDrA2zU\n"
    "KRTuuuEBv1XPAK4DcuDwESHHaRJI6uz2Y78hxs0Fm48S6dJgrnuqeLSqBMXhvUjj\n"
    "iLm9m0c3XY8kR9qFTiGWkOc13OfARJN3v0dmI2epiZriTgUZoSeAB+fxAA837F1B\n"
    "OoXDfMhGa85lWEZuMPsxmaSIeG/OgeRKBOBZ2LMydokBDkg9kNKXOZFhpE99+rZR\n"
    "vmLLBIdLGYNq40LeQIpq9wiwYryBfEalW1NfKFeSPP1li0ntiG1SGD3r11+qkAAW\n"
    "VkFahiFy71sUk3s8wlBt9OOmcW8dynhQxTOlpQpKDQKBgQDn2vjZPT1f1R6hOvj5\n"
    "bxj1qQsv+Gi8tSm5CxK5D8LldK4pI7y/MnABopjKO6MKNHlzOi6suZTdMV7TSF/C\n"
    "6qZM6WmHFaUGu2hVuvGqUvIbeBERGm+MD81Hd9v6IjZEQhsbtSTi+wFBJfuyUVS6\n"
    "Mdnp7fOCSjBcvh0KwDK4plxVpwKBgQDcDtHSmCbzo2LvIOVrlvUR+6NdmIOkdKke\n"
    "/ye6jvZY43gp26Um86wthfrJBGxG3JPAErnoCjZjCeBPLqoAqwFZ8In+2BGZFmAp\n"
    "1QmAIpxtg9R/NLe8RycUsrLx/SXy+vAlekSLBUwBKJ5hInc6JXzMzWOA+zHZIqpe\n"
    "PDhz0mBxpQKBgQDCJlQhna1qNU1716UrQkPVWqO6nLof41g30rTv8OnUONuqKXnh\n"
    "ZTvzspNdLYk+f2h/++Wfz5t/idsM89r0nod5ei9a5d4WABLDT1MUvHZuWCF6f/eO\n"
    "gqD0SsMS91kX2X9XuV1VELkhM8xLqt1XOW1v/Uje/n72+l/ZY85VX0GMmwKBgAKN\n"
    "SXGfwhPhOSx8vSxaO81RlbtoIV6u26c4XkWTktfFC4ewvGGPQdflTds26eqIdE4t\n"
    "6Wn/dFIBs1A3wlDvqrxYRcFm0A1ubP8PMWUDAb1jYft3qQnN6W4cBGc6AE6pCk/k\n"
    "8xaJoTACQJPvymIqPSBC4XyFbTaPaFpfaGgvcF7hAoGAMQ0scVwmlKfrF9/jNg2j\n"
    "jHG3NpPWLQHvLTKbqh0h5Y7ilGk/swZ0OTHHFVaxMT2cojFNvpM9wrh6f2M2k3+F\n"
    "XeGo6LAHvEYHfXLPF3Ym4uBCBfD5CjFjz/9qt/bUaYD+NlWDaGMnsNW5azD+SBik\n"
    "z4Oqpxeyxm0zwtVx/ow55Aw=\n"
    "-----END PRIVATE KEY-----\n";

#endif /* CHTTP_TLS_TEST_MATERIAL_H */
