
if(ENABLE_SANITIZER_ADDRESS)
  if(MSVC)
    add_compile_options(/fsanitize=address)
    add_link_options(/INCREMENTAL:NO)
  else()
    add_compile_options(-fsanitize=address -fno-omit-frame-pointer)
    add_link_options(-fsanitize=address)
  endif()
endif()

foreach(sanitizer IN ITEMS UNDEFINED LEAK THREAD MEMORY)
  if(ENABLE_SANITIZER_${sanitizer})
    string(TOLOWER "${sanitizer}" sanitizer_flag)
    add_compile_options(-fsanitize=${sanitizer_flag} -fno-omit-frame-pointer)
    add_link_options(-fsanitize=${sanitizer_flag})
  endif()
endforeach()
